### ISSUE TITLE
Написать сервисы для получения информации об персоналиях и жанрах

### ISSUE THREAD

**Issue by gryroach** [gryroach/theater-services#6]
Добавить эндпоинты, которые обращаются к Elasticsearch и возвращает информацию о персоналиях и жанрах - по одному или списком.

При запросе списком учитывать параметры фильтрации и сортировки.

Описание и схемы можно найти в уроке Часть команды — часть корабля / Техническое задание на второй модуль ([ссылка на урок](https://practicum.yandex.ru/trainer/middle-python/lesson/b16d863c-1dd2-4c8a-b8df-73b788f39170/)).

Кеширование реализовывать не нужно, будет в рамках другой задачи.

Блокируется задачами #3 #4 #5

Оценка: 8

**Comment by KirillYarkov** [comment]
@gryroach @iamutin в тз кстати не видел примеры search по жанрам, ну это наверно логично, ведь там достаточно фильтрации. А в примере поиска по фильмам нету вывода жанра. Следовательно опускаем пункт про жанры?

**Comment by gryroach** [comment]
> @gryroach @iamutin в тз кстати не видел примеры search по жанрам, ну это наверно логично, ведь там достаточно фильтрации. А в примере поиска по фильмам нету вывода жанра. Следовательно опускаем пункт про жанры?

А что является фильтрацией списка текстовых полей? Это не есть поиск? Просто если у нас есть список жанров из 200, как пользователю быстро найти нужный? 
Можно попробовать сделать общий метод поиска, в который будут прокладываться название индекса и название поля, по которому ищем. В ответе будут все поля и мы засовываем их в модель пайдентика. Ну я так вижу.

**Comment by KirillYarkov** [comment]
@gryroach 
> Можно попробовать сделать общий метод поиска, в который будут прокладываться название индекса и название поля, по которому ищем. В ответе будут все поля и мы засовываем их в модель пайдентика. Ну я так вижу.

Давай попробуем. Типа выносим сервис BaseSearchService вместо методов search у каждой модели, а к нему уже будут непосредственно обращаться другие сервисы передавая дополнительно индекс в качестве аргумента?

Выделяем в подзадачу или могу забрать в рамках текущей задачи?

**Comment by gryroach** [comment]
> Выделяем в подзадачу или могу забрать в рамках текущей задачи?

Давай в рамках отдельной задачи сделаем поиск.
